# -*- eval: (auto-fill-mode 1); -*-
#+TITLE: jupyter-ext
#+AUTHOR: fakeGenius
#+DESCRIPTION: More extensions for emacs jupyter package
#+created: April 01, 2024

A extension package for [[https://github.com/emacs-jupyter/jupyter][jupyter]], which rewrite some functions in
=jupyter-org-extensions.el= with more modern packages (like =transient=, =corfu=
and =consult= etc).

* Intro
1. Why not an extension to org mode?

   Keybindings in this package do actually not restrict to, but it invoke many
   useful functions in =jupyter=. And if one need key menus to navigate between
   blocks, it will be much possible in jupyter session.

* Features
1. transient navigation panel
2. jump src block with =consult=
3. compatibility to =corfu= completion backend (no =company= dependence)
   1) symbol type in =:company-kind=
   2) possible busy completion support

* TODOs
1. [ ] navigate through ~#+CALL:~ block
   There is a type checker inside [[fn:org-next-block]] that block my implement
2. [X] display ansi color of src block result
3. [ ] better =jupyter-org--annotate=
4. [ ] better src block header editing
5. [ ] add grouping and narrowing to =jupyter-org-consult-block=
   maybe by src block language and ~:result~ keyword
6. [ ] highlight current selected block
7. [ ] center after navigation

* Installation
with doom emacs
#+begin_src emacs-lisp :tangle $DOOMDIR/packages.el
(package! jupyter-ext
  :recipe (:host github
           :repo "fakeGenius/jupyter-ext"))
#+end_src

* Configuration
#+begin_src emacs-lisp
(use-package! jupyter+
  :commands jupyter-org-transient
  (map! :map jupyter-org-interaction-mode-map
        :n ";" #'jupyter-org-transient))
#+end_src

* Development
** with =corfu=
what keys are contained in =_jupyter_types_experimental=?
- start / end
- text :: the matched candidates
- signature :: sth. like =(foo arg-a arg-b)=
  the way of function be called
- type :: symbol type of current match
  can be function / variable etc.

Keys of =plist= returned by =completion-at-point= (=company-xxx=)
- doc-buffer
- docsig
- location

** completion-at-point
doc buffer
[[https://github.com/minad/corfu/issues/333][minad/corfu#333 How to add documentation command for corfu-info-documentation...]]

** =complete_reply= api
[[https://github.com/jupyter/jupyter_client/issues/51][jupyter/jupyter_client#51 complete_reply message spec changes: types, values,...]]

* Issues
